export type Language = 'en' | 'ar';

export interface Translations {
  // Landing Page
  welcome: string;
  startChallenge: string;
  createSession: string;
  joinSession: string;
  createSessionDesc: string;
  joinSessionDesc: string;
  alphaQuiz: string;
  alphaQuizDesc: string;

  // Common UI
  loading: string;
  error: string;
  cancel: string;
  confirm: string;
  back: string;
  next: string;
  join: string;
  create: string;

  // Join Page
  joinAsHost: string;
  joinAsPlayer: string;
  sessionCode: string;
  hostCode: string;
  playerName: string;
  selectFlag: string;
  selectTeam: string;
  searching: string;
  hostMobile: string;
  hostMobileDesc: string;
  playerJoin: string;
  playerJoinDesc: string;
  enterSessionCode: string;
  enterHostCode: string;
  enterPlayerName: string;
  flagSearch: string;
  teamSearch: string;
  joinGame: string;
  joiningGame: string;
  gameNotFound: string;
  gameIsFull: string;
  invalidCode: string;
  chooseJoinType: string;
  enterCodeAndName: string;
  enterSessionAndHostCode: string;
  needSessionAndHostCode: string;
  participatingPlayers: string;
  hostCodeFound: string;
  confirmJoinGame: string;
  aboutToJoinGame: string;
  firstPlayer: string;
  secondPlayer: string;
  moveToLobbyWait: string;
  noVideoRoomYet: string;
  contactHostCreateRoom: string;
  failedJoinGame: string;
  errorJoiningGame: string;

  // Create Session Page
  hostName: string;
  gameSettings: string;
  segmentSettings: string;
  questionsPerSegment: string;
  createNewSession: string;
  creatingSession: string;
  sessionCreated: string;
  hostCodeDescription: string;
  hostCodePlaceholder: string;
  hostCodeNote: string;
  sessionId: string;
  sessionIdReady: string;
  sessionIdGenerating: string;
  fillDataAndConfirm: string;
  confirmSession: string;
  waitingSessionCreation: string;
  updating: string;
  enterHostName: string;
  backToHome: string;
  
  // Error messages for Create Session
  configWarning: string;
  featuresNotWorkProperly: string;
  canContinueButProblems: string;
  sessionIdNotGenerated: string;
  cannotCreateSession: string;
  checkSystemSettings: string;
  failedCreateSessionNew: string;
  tryAgain: string;
  connectionFailed: string;
  checkInternetAndTryAgain: string;
  sessionIdAlreadyUsed: string;
  refreshPageAndTryAgain: string;
  connectionTimeout: string;
  
  // Segment names
  segmentWsha: string;
  segmentAuct: string;
  segmentBell: string;
  segmentSing: string;
  segmentRemo: string;

  // Active Games
  activeGames: string;
  noActiveGames: string;
  joinAsHostPlayer: string;
  playersOnline: string;
  created: string;
  quickJoin: string;
  refreshGames: string;

  // Lobby
  waitingForHost: string;
  waitingForPlayers: string;
  gameStarting: string;
  hostControls: string;
  startGame: string;
  lobbyCode: string;
  shareCode: string;

  // Game States
  config: string;
  lobby: string;
  playing: string;
  completed: string;

  // Language Toggle
  language: string;
  english: string;
  arabic: string;
  switchLanguage: string;
  
  // Lobby Page
  waitingLobby: string;
  lobbySessionCode: string;
  connectedPlayers: string;
  videoSystemUpdated: string;
  userInformation: string;
  participantType: string;
  participantName: string;
  participantId: string;
  videoSystemNotes: string;
  roomLinkLoaded: string;
  playerNamesVisible: string;
  videoRoomUsingSession: string;
  cameraControls: string;
  dailyKitchenSink: string;
  
  // Control Room Page
  controlRoom: string;
  playersCode: string;
  controlRoomHostCode: string;
  currentStage: string;
  hostConnected: string;
  hostDisconnected: string;
  controllerActive: string;
  connectedToServer: string;
  controlRoomStartGame: string;
  waitingConfig: string;
  gameAlreadyStarted: string;
  videoRoomReady: string;
  noVideoRoom: string;
  manageVideoLobby: string;
  importantVideoInfo: string;
  controlRoomGameOnly: string;
  videoManagementInLobby: string;
  goToLobby: string;
  showParticipantInfo: string;
  participantInfo: string;
  controlRoomHost: string;
  controlRoomFirstPlayer: string;
  controlRoomSecondPlayer: string;
  notJoinedYet: string;
  videoInteractionTip: string;

  // Video Component Translations
  dailyVideoSystem: string;
  connectionSettings: string;
  roomUrl: string;
  roomUrlAutoLoaded: string;
  roomUrlFromSession: string;
  userName: string;
  userNameFromSession: string;
  userNameLoaded: string;
  preAuthToken: string;
  preAuthTokenAutoGenerated: string;
  preAuthTokenGenerating: string;
  preAuthTokenOptional: string;
  generatingToken: string;
  tokenGenerated: string;
  tokenGenerating: string;
  joinCall: string;
  joiningCall: string;
  leaveCall: string;
  camera: string;
  microphone: string;
  meetingState: string;
  participants: string;
  videosTitle: string;
  waitingForParticipant: string;
  connectedWaiting: string;
  enterRoomAndJoin: string;
  videoSystemReady: string;
  autoLoadedSettings: string;
  roomLinkAutoLoaded: string;
  userNameFromParticipant: string;
  tokenAutoGenerated: string;
  justClickJoin: string;
  videosArrangedVertical: string;
  roomUrlLoaded: string;
  roomUrlNotLoaded: string;
  sessionCreatedSuccessfully: string;
  failedCreateSession: string;
  failedLoadSessionData: string;
  loadingLobby: string;
  noGameIdFound: string;
  loadingVideoComponents: string;
  failedInitVideoComponents: string;
  failedGenerateToken: string;
  failedJoinCall: string;
  failedLeaveCall: string;
  unknownError: string;
  joiningCallMsg: string;
  joinedCallSuccessfully: string;
  leftCall: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    // Landing Page
    welcome: 'Welcome to the Challenge!',
    startChallenge: 'Start the challenge with your friends now!',
    createSession: 'Create New Session',
    joinSession: 'Join Session',
    createSessionDesc: 'Create New Session: You will become the host and control the game',
    joinSessionDesc: 'Join Session: Enter as a player in an existing session',
    alphaQuiz: 'Alpha: Quiz 🚀',
    alphaQuizDesc: 'Alpha Quiz: Simplified version for testing (no video)',

    // Common UI
    loading: 'Loading...',
    error: 'Error',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    join: 'Join',
    create: 'Create',

    // Join Page
    joinAsHost: 'Join as Host',
    joinAsPlayer: 'Join as Player',
    sessionCode: 'Session Code',
    hostCode: 'Host Code',
    playerName: 'Player Name',
    selectFlag: 'Select Flag',
    selectTeam: 'Select Team',
    searching: 'Searching...',
    hostMobile: 'Host (Mobile)',
    hostMobileDesc: 'Join from mobile to see what players see',
    playerJoin: 'Player',
    playerJoinDesc: 'Join as a player in the game',
    enterSessionCode: 'Enter session code',
    enterHostCode: 'Enter host code',
    enterPlayerName: 'Enter your name',
    flagSearch: 'Search countries...',
    teamSearch: 'Search teams...',
    joinGame: 'Join Game',
    joiningGame: 'Joining game...',
    gameNotFound: 'Game not found',
    gameIsFull: 'Game is full',
    invalidCode: 'Invalid code',
    chooseJoinType: 'Choose join type',
    enterCodeAndName: 'Enter game code and name',
    enterSessionAndHostCode: 'Enter session code and host code',
    needSessionAndHostCode: 'You need session code and host code',
    participatingPlayers: 'Participating players in the quiz',
    hostCodeFound: 'You will find the host code on the session setup page',
    confirmJoinGame: 'Confirm joining game',
    aboutToJoinGame: 'You are about to join game',
    firstPlayer: 'first player',
    secondPlayer: 'second player',
    moveToLobbyWait: 'You will be moved to the waiting lobby to start video and wait until the host starts the game.',
    noVideoRoomYet: 'No video room yet. Contact the host to create the room first.',
    contactHostCreateRoom: 'Contact the host to create the room first.',
    failedJoinGame: 'Failed to join game. Try again',
    errorJoiningGame: 'Error occurred while joining game',

    // Create Session Page  
    hostName: 'Host Name',
    gameSettings: 'Game Settings',
    segmentSettings: 'Segment Settings',
    questionsPerSegment: 'Questions per segment',
    createNewSession: 'Create New Session',
    creatingSession: 'Creating session...',
    sessionCreated: 'Session created successfully!',
    hostCodeDescription: 'Host Code (choose it yourself)',
    hostCodePlaceholder: 'Example: MUSAED',
    hostCodeNote: 'Use English letters and numbers only',
    sessionId: 'Session ID',
    sessionIdReady: 'Session ID ready',
    sessionIdGenerating: 'Creating session...',
    fillDataAndConfirm: 'Fill in the data and click confirm to create the session',
    confirmSession: 'Confirm Session',
    waitingSessionCreation: 'Waiting for session creation...',
    updating: 'Updating...',
    enterHostName: 'Enter host name',
    backToHome: 'Back to homepage',
    
    // Error messages for Create Session
    configWarning: 'Warning',
    featuresNotWorkProperly: 'Some features may not work correctly.',
    canContinueButProblems: 'You can continue but may encounter synchronization issues',
    sessionIdNotGenerated: 'Session ID not generated yet. Please wait.',
    cannotCreateSession: 'Cannot create session',
    checkSystemSettings: 'Please check system settings.',
    failedCreateSessionNew: 'Failed to create session. Please try again.',
    tryAgain: 'Try again',
    connectionFailed: 'Connection to server failed. Please check your internet connection and try again.',
    checkInternetAndTryAgain: 'Check internet connection and try again',
    sessionIdAlreadyUsed: 'Session ID already in use. Please refresh the page and try again.',
    refreshPageAndTryAgain: 'Refresh page and try again',
    connectionTimeout: 'Connection timeout. Please try again.',
    
    // Segment names
    segmentWsha: 'What do you know',
    segmentAuct: 'Auction',
    segmentBell: 'Bell section',
    segmentSing: 'Sin & Jeem',
    segmentRemo: 'Compensation',

    // Active Games
    activeGames: 'Active Games',
    noActiveGames: 'No active games found',
    joinAsHostPlayer: 'Join as Host or Player',
    playersOnline: 'players online',
    created: 'Created',
    quickJoin: 'Quick Join',
    refreshGames: 'Refresh Games',

    // Lobby
    waitingForHost: 'Waiting for host...',
    waitingForPlayers: 'Waiting for players...',
    gameStarting: 'Game starting...',
    hostControls: 'Host Controls',
    startGame: 'Start Game',
    lobbyCode: 'Lobby Code',
    shareCode: 'Share this code with players',

    // Game States
    config: 'Configuration',
    lobby: 'Lobby',
    playing: 'Playing',
    completed: 'Completed',

    // Language Toggle
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    switchLanguage: 'Switch Language',
    
    // Lobby Page
    waitingLobby: 'Waiting Lobby',
    lobbySessionCode: 'Session Code',
    connectedPlayers: 'Connected Players',
    videoSystemUpdated: 'Updated video system with player name display',
    userInformation: 'User Information',
    participantType: 'Type',
    participantName: 'Name',
    participantId: 'ID',
    videoSystemNotes: '✅ Updated Video System:',
    roomLinkLoaded: '• Room link automatically loaded from session ID',
    playerNamesVisible: '• Player names displayed below videos',
    videoRoomUsingSession: '• Video room uses session ID directly',
    cameraControls: '• Camera and microphone controls',
    dailyKitchenSink: '• Enhanced Daily.co Kitchen Sink application',
    
    // Control Room Page
    controlRoom: 'Control Room',
    playersCode: 'Players Code',
    controlRoomHostCode: 'Host Code',
    currentStage: 'Current Stage',
    hostConnected: 'Host Connected',
    hostDisconnected: 'Host Disconnected',
    controllerActive: 'Controller Active',
    connectedToServer: 'Connected to Server',
    controlRoomStartGame: 'Start Game',
    waitingConfig: 'Waiting for configuration confirmation...',
    gameAlreadyStarted: 'Game already started',
    videoRoomReady: '✓ Video room ready',
    noVideoRoom: 'No video room',
    manageVideoLobby: 'Manage Video in Lobby',
    importantVideoInfo: 'Important Information - Video Control',
    controlRoomGameOnly: 'This control room is for game management only - does not contain video settings',
    videoManagementInLobby: 'To manage video and interact with players, please use the waiting lobby',
    goToLobby: 'Go to Waiting Lobby',
    showParticipantInfo: 'Show participant information (for reference)',
    participantInfo: 'Participant Information:',
    controlRoomHost: 'Host',
    controlRoomFirstPlayer: 'First Player',
    controlRoomSecondPlayer: 'Second Player',
    notJoinedYet: 'Not joined yet',
    videoInteractionTip: '💡 To interact with video and participants, use the waiting lobby',

    // Video Component Translations
    dailyVideoSystem: 'Daily.co Video System',
    connectionSettings: 'Connection Settings',
    roomUrl: 'Room URL',
    roomUrlAutoLoaded: '✅ (Auto-loaded)',
    roomUrlFromSession: 'Room URL loaded from current session',
    userName: 'User Name',
    userNameFromSession: '✅ (From session info)',
    userNameLoaded: 'Name loaded from participant info',
    preAuthToken: 'Pre-Auth Token',
    preAuthTokenAutoGenerated: '✅ (Auto-generated)',
    preAuthTokenGenerating: '⏳ (Generating...)',
    preAuthTokenOptional: '(Optional)',
    generatingToken: 'Generating login token...',
    tokenGenerated: 'Login token auto-generated',
    tokenGenerating: 'Generating login token...',
    joinCall: 'Join Call',
    joiningCall: 'Joining...',
    leaveCall: 'Leave Call',
    camera: '🎥 Camera',
    microphone: '🎤 Microphone',
    meetingState: 'Meeting Status',
    participants: 'Participants',
    videosTitle: 'Videos (Mobile-Optimized)',
    waitingForParticipant: 'Waiting for participant',
    connectedWaiting: 'Connected, waiting for participants...',
    enterRoomAndJoin: 'Enter room URL and click "Join Call"',
    videoSystemReady: '✅ Enhanced Daily.co Application - Auto Settings',
    autoLoadedSettings: '✅ Updated Daily.co Kitchen Sink App - Auto-load settings',
    roomLinkAutoLoaded: '• Room URL auto-loaded from session',
    userNameFromParticipant: '• User name loaded from participant info',
    tokenAutoGenerated: '• Login token auto-generated',
    justClickJoin: '• Just click "Join Call"',
    videosArrangedVertical: '• Videos arranged vertically with clear numbers',
    roomUrlLoaded: 'Room URL auto-loaded',
    roomUrlNotLoaded: 'Room URL not loaded',
    sessionCreatedSuccessfully: 'Session created successfully',
    failedCreateSession: 'Failed to create session. Check URL validity.',
    failedLoadSessionData: 'Failed to load session data',
    loadingLobby: 'Loading lobby...',
    noGameIdFound: 'No game ID found',
    loadingVideoComponents: 'Loading video components...',
    failedInitVideoComponents: 'Failed to initialize video components',
    failedGenerateToken: 'Failed to generate login token, you can continue without it',
    failedJoinCall: 'Failed to join call',
    failedLeaveCall: 'Error leaving call',
    unknownError: 'Unknown error',
    joiningCallMsg: 'Joining call...',
    joinedCallSuccessfully: 'Successfully joined the call!',
    leftCall: 'Left the call',
  },
  ar: {
    // Landing Page
    welcome: 'مرحباً بكم في التحدي!',
    startChallenge: 'ابدأ التحدي مع أصدقائك الآن!',
    createSession: 'إنشاء جلسة جديدة',
    joinSession: 'الانضمام لجلسة',
    createSessionDesc: 'إنشاء جلسة جديدة: ستصبح المقدم وتتحكم في اللعبة',
    joinSessionDesc: 'الانضمام لجلسة: ادخل كلاعب في جلسة موجودة',
    alphaQuiz: 'Alpha: Quiz 🚀',
    alphaQuizDesc: 'Alpha Quiz: نسخة مبسطة للاختبار (بدون فيديو)',

    // Common UI
    loading: 'جاري التحميل...',
    error: 'خطأ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    join: 'انضمام',
    create: 'إنشاء',

    // Join Page
    joinAsHost: 'انضمام كمقدم',
    joinAsPlayer: 'انضمام كلاعب',
    sessionCode: 'كود الجلسة',
    hostCode: 'كود المقدم',
    playerName: 'اسم اللاعب',
    selectFlag: 'اختر العلم',
    selectTeam: 'اختر الفريق',
    searching: 'جاري البحث...',
    hostMobile: 'مقدم (جوال)',
    hostMobileDesc: 'انضم من الجوال لرؤية ما يراه اللاعبون',
    playerJoin: 'لاعب',
    playerJoinDesc: 'انضم كلاعب في اللعبة',
    enterSessionCode: 'أدخل كود الجلسة',
    enterHostCode: 'أدخل كود المقدم',
    enterPlayerName: 'أدخل اسمك',
    flagSearch: 'ابحث عن الدول...',
    teamSearch: 'ابحث عن الفرق...',
    joinGame: 'انضمام للعبة',
    joiningGame: 'جاري الانضمام...',
    gameNotFound: 'اللعبة غير موجودة',
    gameIsFull: 'اللعبة ممتلئة',
    invalidCode: 'كود غير صحيح',
    chooseJoinType: 'اختر نوع الانضمام',
    enterCodeAndName: 'أدخل رمز اللعبة والاسم',
    enterSessionAndHostCode: 'أدخل رمز الجلسة ورمز المقدم',
    needSessionAndHostCode: 'تحتاج رمز الجلسة ورمز المقدم',
    participatingPlayers: 'للاعبين المشاركين في المسابقة',
    hostCodeFound: 'ستجد رمز المقدم في صفحة إعداد الجلسة',
    confirmJoinGame: 'تأكيد الانضمام للعبة',
    aboutToJoinGame: 'أنت على وشك الانضمام للعبة',
    firstPlayer: 'لاعب أول',
    secondPlayer: 'لاعب ثاني',
    moveToLobbyWait: 'سيتم نقلك إلى صالة الانتظار لبدء الفيديو والانتظار حتى يبدأ المقدم اللعبة.',
    noVideoRoomYet: 'لا توجد غرفة فيديو بعد.',
    contactHostCreateRoom: 'اتصل بالمقدم لإنشاء الغرفة أولاً.',
    failedJoinGame: 'فشل في الانضمام للعبة. حاول مرة أخرى',
    errorJoiningGame: 'حدث خطأ أثناء الانضمام للعبة',

    // Create Session Page
    hostName: 'اسم المقدم',
    gameSettings: 'إعدادات اللعبة',
    segmentSettings: 'إعدادات الأجزاء',
    questionsPerSegment: 'الأسئلة لكل جزء',
    createNewSession: 'إنشاء جلسة جديدة',
    creatingSession: 'جاري إنشاء الجلسة...',
    sessionCreated: 'تم إنشاء الجلسة بنجاح!',
    hostCodeDescription: 'رمز المقدم (اختره بنفسك)',
    hostCodePlaceholder: 'مثال: MUSAED',
    hostCodeNote: 'استخدم أحرف إنجليزية وأرقام فقط',
    sessionId: 'معرف الجلسة',
    sessionIdReady: 'معرف الجلسة جاهز',
    sessionIdGenerating: 'جاري إنشاء الجلسة...',
    fillDataAndConfirm: 'املأ البيانات واضغط تأكيد لإنشاء الجلسة',
    confirmSession: 'تأكيد الجلسة',
    waitingSessionCreation: 'انتظار إنشاء الجلسة...',
    updating: 'جاري التحديث...',
    enterHostName: 'أدخل اسم المقدم',
    backToHome: 'العودة للصفحة الرئيسية',
    
    // Error messages for Create Session
    configWarning: 'تحذير',
    featuresNotWorkProperly: 'قد لا تعمل بعض الميزات بشكل صحيح.',
    canContinueButProblems: 'يمكنك المتابعة ولكن قد تواجه مشاكل في المزامنة',
    sessionIdNotGenerated: 'لم يتم إنشاء معرف الجلسة بعد. يرجى الانتظار.',
    cannotCreateSession: 'لا يمكن إنشاء جلسة',
    checkSystemSettings: 'يرجى التحقق من إعدادات النظام.',
    failedCreateSessionNew: 'فشل في إنشاء الجلسة. يرجى المحاولة مرة أخرى.',
    tryAgain: 'حاول مرة أخرى',
    connectionFailed: 'فشل في الاتصال بالخادم. يرجى التحقق من اتصال الإنترنت والمحاولة مرة أخرى.',
    checkInternetAndTryAgain: 'تحقق من اتصال الإنترنت وحاول مرة أخرى',
    sessionIdAlreadyUsed: 'معرف الجلسة مستخدم بالفعل. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    refreshPageAndTryAgain: 'حدث الصفحة وحاول مرة أخرى',
    connectionTimeout: 'انتهت مهلة الاتصال. يرجى المحاولة مرة أخرى.',
    
    // Segment names
    segmentWsha: 'وش تعرف',
    segmentAuct: 'المزاد',
    segmentBell: 'فقرة الجرس',
    segmentSing: 'سين وجيم',
    segmentRemo: 'التعويض',

    // Active Games
    activeGames: 'الألعاب النشطة',
    noActiveGames: 'لا توجد ألعاب نشطة',
    joinAsHostPlayer: 'انضم كمقدم أو لاعب',
    playersOnline: 'لاعبين متصلين',
    created: 'تم الإنشاء',
    quickJoin: 'انضمام سريع',
    refreshGames: 'تحديث الألعاب',

    // Lobby
    waitingForHost: 'في انتظار المقدم...',
    waitingForPlayers: 'في انتظار اللاعبين...',
    gameStarting: 'اللعبة تبدأ...',
    hostControls: 'تحكم المقدم',
    startGame: 'بدء اللعبة',
    lobbyCode: 'كود الغرفة',
    shareCode: 'شارك هذا الكود مع اللاعبين',

    // Game States
    config: 'إعداد',
    lobby: 'غرفة الانتظار',
    playing: 'جاري اللعب',
    completed: 'مكتملة',

    // Language Toggle
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    switchLanguage: 'تغيير اللغة',
    
    // Lobby Page
    waitingLobby: 'صالة الانتظار',
    lobbySessionCode: 'رمز الجلسة',
    connectedPlayers: 'اللاعبون المتصلون',
    videoSystemUpdated: 'نظام الفيديو المحدث مع عرض أسماء اللاعبين',
    userInformation: 'معلومات المستخدم',
    participantType: 'النوع',
    participantName: 'الاسم',
    participantId: 'المعرف',
    videoSystemNotes: '✅ نظام الفيديو المحدث:',
    roomLinkLoaded: '• رابط الغرفة يتم تحميله تلقائياً من معرف الجلسة',
    playerNamesVisible: '• أسماء اللاعبين تظهر أسفل مقاطع الفيديو',
    videoRoomUsingSession: '• غرفة الفيديو تستخدم معرف الجلسة مباشرة',
    cameraControls: '• تحكم في الكاميرا والميكروفون',
    dailyKitchenSink: '• تطبيق Daily.co Kitchen Sink المطور',
    
    // Control Room Page
    controlRoom: 'غرفة التحكم',
    playersCode: 'رمز اللاعبين',
    controlRoomHostCode: 'رمز المقدم',
    currentStage: 'المرحلة الحالية',
    hostConnected: 'المقدم متصل',
    hostDisconnected: 'المقدم غير متصل',
    controllerActive: 'تحكم نشط',
    connectedToServer: 'متصل بالخادم',
    controlRoomStartGame: 'ابدأ اللعبة',
    waitingConfig: 'في انتظار تأكيد البيانات...',
    gameAlreadyStarted: 'اللعبة بدأت فعلاً',
    videoRoomReady: '✓ غرفة الفيديو جاهزة',
    noVideoRoom: 'لا توجد غرفة فيديو',
    manageVideoLobby: 'إدارة الفيديو في الصالة',
    importantVideoInfo: 'معلومات هامة - التحكم في الفيديو',
    controlRoomGameOnly: 'هذه غرفة التحكم للعبة فقط - لا تحتوي على إعدادات الفيديو',
    videoManagementInLobby: 'لإدارة الفيديو والمشاركة مع اللاعبين، يرجى استخدام صالة الانتظار',
    goToLobby: 'الذهاب لصالة الانتظار',
    showParticipantInfo: 'عرض معلومات المشاركين (للمرجع)',
    participantInfo: 'معلومات المشاركين:',
    controlRoomHost: 'المقدم',
    controlRoomFirstPlayer: 'اللاعب الأول',
    controlRoomSecondPlayer: 'اللاعب الثاني',
    notJoinedYet: 'لم ينضم بعد',
    videoInteractionTip: '💡 للتفاعل مع الفيديو والمشاركين، استخدم صالة الانتظار',

    // Video Component Translations
    dailyVideoSystem: 'نظام Daily.co للفيديو',
    connectionSettings: 'إعدادات الاتصال',
    roomUrl: 'رابط الغرفة',
    roomUrlAutoLoaded: '✅ (تم التحميل تلقائياً)',
    roomUrlFromSession: 'تم تحميل رابط الغرفة من الجلسة الحالية',
    userName: 'اسم المستخدم',
    userNameFromSession: '✅ (من معلومات الجلسة)',
    userNameLoaded: 'تم تحميل الاسم من معلومات المشارك',
    preAuthToken: 'رمز التحقق المسبق',
    preAuthTokenAutoGenerated: '✅ (تم الإنشاء تلقائياً)',
    preAuthTokenGenerating: '⏳ (جاري الإنشاء...)',
    preAuthTokenOptional: '(اختياري)',
    generatingToken: 'جاري إنشاء رمز الدخول...',
    tokenGenerated: 'تم إنشاء رمز الدخول تلقائياً',
    tokenGenerating: 'جاري إنشاء رمز الدخول...',
    joinCall: 'انضمام للمكالمة',
    joiningCall: 'جاري الانضمام...',
    leaveCall: 'مغادرة المكالمة',
    camera: '🎥 كاميرا',
    microphone: '🎤 ميكروفون',
    meetingState: 'حالة الاجتماع',
    participants: 'المشاركون',
    videosTitle: 'الفيديوهات (محسّن للهواتف الذكية)',
    waitingForParticipant: 'في انتظار المشارك',
    connectedWaiting: 'متصل، في انتظار المشاركين...',
    enterRoomAndJoin: 'أدخل رابط الغرفة وانقر "انضمام للمكالمة"',
    videoSystemReady: '✅ تطبيق Daily.co المحسن - تحميل تلقائي للإعدادات',
    autoLoadedSettings: '✅ تطبيق Daily.co Kitchen Sink المحسن - تحميل تلقائي للإعدادات',
    roomLinkAutoLoaded: '• رابط الغرفة محمل تلقائياً من الجلسة',
    userNameFromParticipant: '• اسم المستخدم محمل من معلومات المشارك',
    tokenAutoGenerated: '• رمز الدخول يتم إنشاؤه تلقائياً',
    justClickJoin: '• كل ما عليك فعله هو الضغط على "انضمام للمكالمة"',
    videosArrangedVertical: '• الفيديوهات مرتبة عمودياً مع أرقام واضحة',
    roomUrlLoaded: 'تم تحميل رابط الغرفة تلقائياً',
    roomUrlNotLoaded: 'لم يتم تحميل رابط الغرفة',
    sessionCreatedSuccessfully: 'تم إنشاء جلسة جديدة بنجاح',
    failedCreateSession: 'فشل في إنشاء جلسة جديدة. تحقق من صحة الرابط.',
    failedLoadSessionData: 'فشل في تحميل بيانات الجلسة',
    loadingLobby: 'جاري تحميل الصالة...',
    noGameIdFound: 'لا يوجد معرف للعبة',
    loadingVideoComponents: 'جاري تهيئة مكونات الفيديو...',
    failedInitVideoComponents: 'فشل في تهيئة مكونات الفيديو',
    failedGenerateToken: 'تعذر إنشاء رمز الدخول، يمكنك المتابعة بدونه',
    failedJoinCall: 'فشل في الانضمام للمكالمة',
    failedLeaveCall: 'خطأ في مغادرة المكالمة',
    unknownError: 'خطأ غير معروف',
    joiningCallMsg: 'جاري الانضمام للمكالمة...',
    joinedCallSuccessfully: 'تم الانضمام للمكالمة بنجاح!',
    leftCall: 'تم مغادرة المكالمة',
  },
};

export const getTranslation = (language: Language, key: keyof Translations): string => {
  return translations[language][key];
};