name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Install Supabase CLI as dev dependency
        run: npm install supabase --save-dev

      - name: Verify Supabase CLI
        run: npx supabase --version || true

      - name: Validate build (allow errors)
        run: npm run build
        continue-on-error: true

      - name: Run lint and tests
        run: npm test || npm run lint
        continue-on-error: true
